apiVersion: v2
name: market-tracker-api
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: app_deployment
    version: 2.5.3
    repository: https://nexus-craigmiller160.ddns.net/repository/helm-private