app_deployment:
  appName: market-tracker-api
  image: nexus-docker-craigmiller160.ddns.net/market-tracker-api:latest
  configMap:
    NODE_ENV: production
    MONGO_HOSTNAME: mongodb.infra-prod
    MONGO_AUTH_DB: admin
    MONGO_PORT: "27017"
    MONGO_DB: market_tracker_prod
    EXPRESS_PORT: "8080"
    AUTH_SERVER_HOST: https://auth-craigmiller160.ddns.net
    REALM: apps-prod
    TRADIER_BASE_URL: "https://sandbox.tradier.com/v1"
    COIN_GECKO_BASE_URL: "https://api.coingecko.com/api/v3"
  onepassworditems:
    - name: market-tracker-api-oauth2-keys
      itemPath: vaults/Home Server (Prod)/items/Market Tracker API OAuth2 Keys
    - name: market-tracker-tradier-api-key
      itemPath: vaults/Home Server (Prod)/items/Market Tracker Tradier API Key
    - name: market-tracker-mongodb
      itemPath: vaults/Home Server (Prod)/items/MongoDB Root Account
  ports:
    - containerPort: 8080
  secrets:
    - envVariable: MONGO_USER
      secretName: market-tracker-mongodb
      secretKey: username
    - envVariable: MONGO_PASSWORD
      secretName: market-tracker-mongodb
      secretKey: password
    - envVariable: CLIENT_ID
      secretName: market-tracker-api-oauth2-keys
      secretKey: kcClientId
    - envVariable: CLIENT_SECRET
      secretName: market-tracker-api-oauth2-keys
      secretKey: kcClientSecret
    - envVariable: TRADIER_API_KEY
      secretName: market-tracker-tradier-api-key
      secretKey: apiKey
  livenessProbe:
    httpGet:
      path: /healthcheck
      port: 8080
      scheme: HTTPS