version: '3.5'

services:
  mongo:
    image: mongo:6.0.1
    container_name: market_tracker_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27017:27017'