apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-management-service-configmap
data:
  spring.profiles.active: prod
  spring.config.location: classpath:/config/common/,classpath:/config/prod/
  spring.datasource.host: postgres.infra-prod
  spring.datasource.port: "5432"
  oauth2.auth-server-host: https://sso-oauth2-server:8443
