apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-k8s-bug-demo-config
data:
  NODE_ENV: production
  MONGO_USER: mongo_root
  MONGO_HOSTNAME: mongodb-service
  MONGO_AUTH_DB: admin
  MONGO_PORT: "27017"
  MONGO_DB: market_tracker_prod
  EXPRESS_PORT: "8080"
  AUTH_SERVER_HOST: https://sso-oauth2-server-service:8443
  CLIENT_KEY: 47655159-645a-4c53-9a9c-28bbc1bacd5c
  CLIENT_SECRET: e8ea960f-0031-425b-8a52-2bf5e7a0085a
  CLIENT_NAME: market-tracker-api
  AUTH_CODE_REDIRECT_URI: "/market-tracker/api/oauth/authcode/code"
  AUTH_LOGIN_BASE_URI: "/market-tracker/oauth2"
  COOKIE_NAME: market-tracker-token
  COOKIE_MAX_AGE_SECS: 86400
  COOKIE_PATH: "/market-tracker"
  POST_AUTH_REDIRECT: "/market-tracker"