apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-tracker-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-tracker-api
  template:
    metadata:
      labels:
        app: market-tracker-api
    spec:
      containers:
        - name: market-tracker-api
          image: craigmiller160.ddns.net:30004/market-tracker-api:${KUBE_IMG_VERSION}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: market-tracker-api-config
          env:
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-root-password
                  key: MONGO_ROOT_PASSWORD
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: market-tracker-api-client-secret
                  key: client-secret
            - name: TRADIER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: tradier-api-key-secret
                  key: tradier-api-key
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 300
---
apiVersion: v1
kind: Service
metadata:
  name: market-tracker-api-service
spec:
  type: NodePort
  selector:
    app: market-tracker-api
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30009
      protocol: TCP
