apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-k8s-bug-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-k8s-bug-demo
  template:
    metadata:
      labels:
        app: mongo-k8s-bug-demo
    spec:
      containers:
        - name: mongo-k8s-bug-demo
          image: craigmiller160.ddns.net:30004/mongo-k8s-bug-demo:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: mongo-k8s-bug-demo-config
          env:
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-root-password
                  key: MONGO_ROOT_PASSWORD
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 300
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-k8s-bug-demo-service
spec:
  type: NodePort
  selector:
    app: mongo-k8s-bug-demo
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30009
      protocol: TCP
